language: ruby
cache: bundler
branches:
  only:
  - master
  - dev
rvm:
- 2.4.0
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: script
  script: deploy_integration.sh
  on:
    branch: dev
before_install:
  - openssl aes-256-cbc -K $encrypted_e539786aa59d_key -iv $encrypted_e539786aa59d_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
