language: ruby
branches:
  only:
  - master
rvm:
  - 2.4.0
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: kolhoosidb-api
 run:
  - "rake db:migrate"
